### ISSUE TITLE
GraphQL: Request for findChapterById

### ISSUE THREAD

**Issue by mizaki** [hummingbird-me/kitsu-server#1442]
I should imagine one for `findEpisodeById` would be useful too.

**Comment by shomykohai** [comment]
In what context would it be useful to find an episode by its ID (like in the frontend)?
Maybe when looking at the description of a certain chapter like it's already possible with json API?

Would like to have more details so I could make a PR myself in case :D!

**Comment by mizaki** [comment]
Sure thing. First (if it matters), APIs such as [MangaDex](https://api.mangadex.org/docs/redoc.html#tag/Chapter/operation/get-chapter-id), [CV](https://comicvine.gamespot.com/api/documentation#toc-0-10) and others have it.

In the case of [comictagger](https://github.com/comictagger/comictagger) the `issue_id` (chapter/issue being synonyms in this case) is used internally as a single identifier (everything can then be derived from there). There is also the option on the CLI to "tag" from an `issue id`.

Granted, usually the reason for this is that only the minimal information is retrieved in the first instance and then further information (characters, credits, et al) is retrieved via the full call but there isn't a lot of extra chapter information to collect (currently?) from Kitsu.

I have worked around it internally but the CLI option will fail.

Making up a maybe tenuous example:
Currently the Kitsu website does a `https://kitsu.io/api/edge/chapters?filter[manga_id]=33607&filter[number]=1` and uses `<a href="/manga/maho-maho/chapters/1">` to get chapter information but using an `chapter id` would be cleaner(?). Also could allow for a `/manga/maho-maho/<chapter id>` similar to `/manga/<slug>` or `/manga/<id>`.

**Comment by shomykohai** [comment]
> Making up a maybe tenuous example:
Currently the Kitsu website does a https://kitsu.io/api/edge/chapters?filter[manga_id]=33607&filter[number]=1 and uses <a href="/manga/maho-maho/chapters/1"> to get chapter information but using an chapter id would be cleaner(?). Also could allow for a /manga/maho-maho/<chapter id> similar to /manga/<slug> or /manga/<id>.

As for that wouldn't be easier to just use the `chapter` field in Type::Manga? Since it accepts `:number` as an argument to fetch a specific chapter
```graphql
query fetchChapter($mangaId: ID!, $number: Integer!){
    findMangaById(id: $mangaId){
          chapter(number: $number){
               ...
           }
    } 
}
```

but anyway I understand there're other contexts where it might be useful to use the id instead of the number
