### ISSUE TITLE
GraphQL: Add description to Volume type and expose thumbnails

### ISSUE THREAD

**Issue by mizaki** [hummingbird-me/kitsu-server#1446]
Few, if any, chapters will have an official description and so relies on users to create them. Volumes on the other hand, will usually have descriptions created by the publisher.

Similarly to the above and it seems that the DB has an image field for volumes but isn't exposed via GQL.

**Comment by shomykohai** [comment]
> Few, if any, chapters will have an official description and so relies on users to create them. Volumes on the other hand, will usually have descriptions created by the publisher.

As you pointed out, currently [volumes don't have a description column](https://github.com/hummingbird-me/kitsu-server/blob/the-future/db/schema.rb#L1617).
I'd suggest you to ask on the #dev channel on the discord server if that field is planned or not for Kitsu V4.

For what is my personal opinion though I stand with your idea, and if turns out it's planned I could do a PR to add it (if no one else does before) when I have some free time to work on kitsu!

> Similarly to the above and it seems that the DB has an image field for volumes but isn't exposed via GQL.

That should be a fairly simple edit to types/volume.rb
it's the same approach of this! 
https://github.com/hummingbird-me/kitsu-server/blob/the-future/app/graphql/types/interface/unit.rb#L29-L30

If you could make a PR it would be good since right now I'm unable to
